#!/bin/bash

#/************************************************************************
# * Copyright (c) 2013 doujinshuai (doujinshuai@gmail.com)
# * Create Time   : 01-31-2013
# * Last Modified : 02-25-2013
# ************************************************************************/

# Return codes:
STATE_OK=0
STATE_WARNING=1
STATE_CRITICAL=2
STATE_UNKNOWN=3

ErrInfo=$(dmesg |grep error)

if [ $(echo $ErrInfo|wc -l) -ne 0 ]
then
        echo "no error output"
        exit ${STATE_OK}
else
        echo $ErrInfo
        exit ${STATE_WARNING}
fi
